version: "3.8"

services:
  backend:
    build:
      context: ./Deploy/backend_api
      dockerfile: Dockerfile
    container_name: bluegridocr_backend
    restart: unless-stopped
    env_file:
      - ./Deploy/backend_api/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    container_name: bluegridocr_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
