ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS fk_usuario_creador INTEGER REFERENCES usuarios(id_usuario);

ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS estado_validacion TEXT DEFAULT 'PENDIENTE_VALIDACION';

ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS validated_at TIMESTAMP;

ALTER TABLE registros_ocr
ADD COLUMN IF NOT EXISTS validated_by INTEGER REFERENCES usuarios(id_usuario);
